import React from "react";
import { Link } from "react-router-dom";
import { Brain, Target, TrendingUp, BookOpen, GraduationCap, ChevronRight } from "lucide-react";
import { motion } from "motion/react";

export default function Home({ user }: { user: any }) {
  return (
    <div className="max-w-6xl mx-auto py-12 px-4">
      {/* Hero Section */}
      <div className="flex flex-col lg:flex-row items-center gap-12 mb-24">
        <motion.div 
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6 }}
          className="flex-1 text-center lg:text-left"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 border border-indigo-100 text-indigo-700 text-sm font-semibold mb-6">
            <GraduationCap className="w-4 h-4" />
            <span>Maharashtra SSC Class 10 Maths</span>
          </div>
          <h1 className="text-5xl lg:text-7xl font-extrabold text-slate-900 leading-tight mb-6">
            Master Mathematics with <span className="text-indigo-600">AI-Powered</span> Quizzes
          </h1>
          <p className="text-xl text-slate-600 mb-10 max-w-2xl leading-relaxed">
            Personalized, chapter-wise quizzes generated by Gemini AI to help you excel in your SSC Board Exams. Track your progress and identify weak areas instantly.
          </p>
          <div className="flex flex-col sm:flex-row items-center gap-4 justify-center lg:justify-start">
            {user ? (
              <Link to="/quiz-setup" className="px-8 py-4 bg-indigo-600 text-white rounded-xl font-bold text-lg hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 flex items-center gap-2">
                Start a Quiz <ChevronRight className="w-5 h-5" />
              </Link>
            ) : (
              <>
                <Link to="/register" className="px-8 py-4 bg-indigo-600 text-white rounded-xl font-bold text-lg hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 flex items-center gap-2">
                  Get Started for Free <ChevronRight className="w-5 h-5" />
                </Link>
                <Link to="/login" className="px-8 py-4 bg-white text-slate-700 border border-slate-200 rounded-xl font-bold text-lg hover:bg-slate-50 transition-all">
                  Sign In
                </Link>
              </>
            )}
          </div>
        </motion.div>
        
        <motion.div 
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="flex-1 relative"
        >
          <div className="bg-white p-8 rounded-3xl shadow-2xl border border-slate-100 relative z-10">
            <div className="flex items-center justify-between mb-8">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-indigo-100 rounded-2xl flex items-center justify-center text-indigo-600">
                  <Brain className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="font-bold text-slate-800">AI Generator</h3>
                  <p className="text-xs text-slate-500">Powered by Gemini</p>
                </div>
              </div>
              <div className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-xs font-bold">Live</div>
            </div>
            
            <div className="space-y-4">
              {[
                { label: "Chapter", value: "Trigonometry" },
                { label: "Difficulty", value: "Medium" },
                { label: "Questions", value: "20" }
              ].map((item, i) => (
                <div key={i} className="p-4 bg-slate-50 rounded-xl border border-slate-100 flex items-center justify-between">
                  <span className="text-sm text-slate-500 font-medium">{item.label}</span>
                  <span className="text-sm text-slate-800 font-bold">{item.value}</span>
                </div>
              ))}
            </div>
            
            <div className="mt-8 pt-6 border-t border-slate-100">
              <div className="flex items-center justify-between text-sm mb-2">
                <span className="text-slate-500 font-medium">Generation Progress</span>
                <span className="text-indigo-600 font-bold">100%</span>
              </div>
              <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: "100%" }}
                  transition={{ duration: 1.5, delay: 0.8 }}
                  className="h-full bg-indigo-600"
                />
              </div>
            </div>
          </div>
          
          {/* Decorative elements */}
          <div className="absolute -top-6 -right-6 w-32 h-32 bg-indigo-400/10 rounded-full blur-3xl" />
          <div className="absolute -bottom-10 -left-10 w-48 h-48 bg-indigo-600/5 rounded-full blur-3xl" />
        </motion.div>
      </div>

      {/* Features Section */}
      <div className="grid md:grid-cols-3 gap-8 mb-24">
        {[
          {
            icon: <Target className="w-6 h-6" />,
            title: "Syllabus Focused",
            desc: "Strictly follows the Maharashtra State Board Class 10 Maths syllabus (Algebra & Geometry)."
          },
          {
            icon: <Brain className="w-6 h-6" />,
            title: "AI Generated",
            desc: "Dynamic questions generated by Gemini AI ensure you never see the same quiz twice."
          },
          {
            icon: <TrendingUp className="w-6 h-6" />,
            title: "Performance Tracking",
            desc: "Detailed analytics and performance graphs to help you identify and improve your weak chapters."
          }
        ].map((feature, i) => (
          <motion.div 
            key={i}
            whileHover={{ y: -5 }}
            className="p-8 bg-white rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-all"
          >
            <div className="w-12 h-12 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600 mb-6">
              {feature.icon}
            </div>
            <h3 className="text-xl font-bold text-slate-800 mb-3">{feature.title}</h3>
            <p className="text-slate-600 leading-relaxed">{feature.desc}</p>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
